Install kde languagepack

diff --git a/freebsd-desktop b/freebsd-desktop
--- a/freebsd-desktop
+++ b/freebsd-desktop
@@ -101,6 +101,16 @@ else
 		echo "+ dbus enabled in $RCCONF"
 	fi
 fi
+PACKAGESUFFIX=-kde-l10n
+PACKAGENAME=${COUNTRYCODE}${PACKAGESUFFIX}
+if pkg search ${PACKAGENAME} | grep -q "${PACKAGENAME}"; then
+	echo "Trying to install the KDE-languagepack for $COUNTRYCODE"
+	pkg install -y ${PACKAGENAME} \
+	&& echo "+ ${PACKAGENAME} installed" \
+	|| echo "! could not install ${PACKAGENAME}"
+else
+	echo "! There is no KDE-languagepack for $COUNTRYCODE. Please choose one and install it by hand if needed."
+fi
 
 
 #+ language
